name: build and deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: pnpm/action-setup@v3
        with:
          version: 8.15.6
      - name: Setup Node.js
        uses: actions/setup-node@v4

      - name: Install dependencies
        run: pnpm install

      - name: Build
        run: pnpm build

      - name: create a short SHA
        run: echo "SHORT_SHA=$(echo $GITHUB_SHA | cut -c1-7)" >> $GITHUB_ENV

      # upload as github release
      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: dist/*
          tag_name: ${{ env.SHORT_SHA }}
